import type { ThemePalette } from '@/src/theme/colors';

export type IconCategory = 'market' | 'trading' | 'account' | 'risk' | 'kyc' | 'funds' | 'system-navigation' | 'support-ops';
export type IconPlatform = 'app' | 'h5' | 'web' | 'admin';
export type IconTone = 'text' | 'textMuted' | 'textDim' | 'brand' | 'blue' | 'amber' | 'danger' | 'up' | 'down' | 'white' | 'panel';
export type IconProvider = 'hugeicons-free-stroke-rounded' | 'hugeicons-pro-duotone-rounded';
export type IconStyle = 'stroke-rounded' | 'duotone-rounded' | 'twotone-rounded';
export type IconVisualWeight = 'micro' | 'navigation' | 'functional' | 'financial-core' | 'supporting';

export type AppIconDefinition = {
  category: IconCategory;
  provider: IconProvider;
  providerIcon: string;
  proProviderIcon: string;
  style: IconStyle;
  platforms: IconPlatform[];
  defaultSize: number;
  allowedTones: IconTone[];
  primaryTone: IconTone;
  secondaryTone: IconTone;
  strokeWidth: number;
  visualWeight: IconVisualWeight;
  financeSemanticScore: number;
  states: string[];
  usage: string;
  forbidden: string[];
  deprecated: boolean;
  replacement?: string;
};

const base = {
  platforms: ['app', 'h5', 'web'] as IconPlatform[],
  provider: 'hugeicons-free-stroke-rounded' as IconProvider,
  style: 'stroke-rounded' as IconStyle,
};

export const iconRegistry = {
  appApple: { ...base, providerIcon: 'AppleIcon', proProviderIcon: 'AppleIcon', category: 'system-navigation', defaultSize: 17, allowedTones: ['text'], primaryTone: 'text', secondaryTone: 'textDim', strokeWidth: 1.75, visualWeight: 'navigation', financeSemanticScore: 7, states: ['default'], usage: 'Apple sign-in provider mark.', forbidden: ['Do not recolor as risk or market status.'], deprecated: false },
  actionRefresh: { ...base, providerIcon: 'ArrowReloadHorizontalIcon', proProviderIcon: 'ArrowReloadHorizontalIcon', category: 'system-navigation', defaultSize: 20, allowedTones: ['amber', 'textDim'], primaryTone: 'textDim', secondaryTone: 'amber', strokeWidth: 1.75, visualWeight: 'functional', financeSemanticScore: 7, states: ['default', 'loading'], usage: 'Refresh, withdraw-style cycle, or reload action.', forbidden: ['Do not use for price trend.'], deprecated: false },
  transferSwitch: { ...base, providerIcon: 'Exchange03Icon', proProviderIcon: 'Exchange03Icon', category: 'funds', defaultSize: 20, allowedTones: ['blue', 'text', 'brand'], primaryTone: 'blue', secondaryTone: 'textDim', strokeWidth: 1.8, visualWeight: 'financial-core', financeSemanticScore: 9, states: ['default', 'pressed', 'disabled'], usage: 'Transfer, swap, or two-way movement between accounts.', forbidden: ['Do not use for market volatility.'], deprecated: false },
  accountBank: { ...base, providerIcon: 'Wallet01Icon', proProviderIcon: 'Wallet01Icon', category: 'funds', defaultSize: 18, allowedTones: ['text', 'textDim', 'blue'], primaryTone: 'text', secondaryTone: 'blue', strokeWidth: 1.8, visualWeight: 'financial-core', financeSemanticScore: 9, states: ['default', 'selected', 'disabled'], usage: 'Wallet, account balance, funding account, or account capital.', forbidden: ['Do not use for generic profile, archive, or institution-only meaning.'], deprecated: false },
  notificationBell: { ...base, providerIcon: 'Notification02Icon', proProviderIcon: 'Notification02Icon', category: 'system-navigation', defaultSize: 16, allowedTones: ['textMuted', 'textDim'], primaryTone: 'textMuted', secondaryTone: 'textDim', strokeWidth: 1.7, visualWeight: 'navigation', financeSemanticScore: 7, states: ['default', 'unread', 'disabled'], usage: 'Notifications entry.', forbidden: ['Do not use for alert risk severity; use riskShield or infoCircle.'], deprecated: false },
  expandDown: { ...base, providerIcon: 'ArrowDown01Icon', proProviderIcon: 'ArrowDown01Icon', category: 'system-navigation', defaultSize: 14, allowedTones: ['text', 'textDim'], primaryTone: 'textDim', secondaryTone: 'textDim', strokeWidth: 1.7, visualWeight: 'micro', financeSemanticScore: 6, states: ['default', 'expanded', 'collapsed'], usage: 'Dropdown or expandable control. Use the chevron-style down arrow without a shaft for global dropdown affordances.', forbidden: ['Do not use as next navigation.', 'Do not use shafted down arrows for dropdown controls.'], deprecated: false },
  navigateBack: { ...base, providerIcon: 'ArrowLeft02Icon', proProviderIcon: 'ArrowLeft02Icon', category: 'system-navigation', defaultSize: 22, allowedTones: ['text', 'textMuted'], primaryTone: 'text', secondaryTone: 'textDim', strokeWidth: 1.7, visualWeight: 'navigation', financeSemanticScore: 6, states: ['default', 'pressed', 'disabled'], usage: 'Back navigation.', forbidden: ['Do not use for previous market movement.'], deprecated: false },
  navigateNext: { ...base, providerIcon: 'ArrowRight01Icon', proProviderIcon: 'ArrowRight01Icon', category: 'system-navigation', defaultSize: 16, allowedTones: ['text', 'textDim', 'panel'], primaryTone: 'textDim', secondaryTone: 'textDim', strokeWidth: 1.7, visualWeight: 'micro', financeSemanticScore: 6, states: ['default', 'pressed', 'disabled'], usage: 'Next row navigation and disclosure. Use the chevron-style arrow without a shaft for global row guidance.', forbidden: ['Do not use for market up/down state.', 'Do not use shafted arrows for row disclosure.'], deprecated: false },
  marketTrend: { ...base, providerIcon: 'ChartCandlestickIcon', proProviderIcon: 'ChartCandlestickIcon', category: 'market', defaultSize: 20, allowedTones: ['brand', 'up', 'down', 'text', 'textDim'], primaryTone: 'brand', secondaryTone: 'textDim', strokeWidth: 1.8, visualWeight: 'financial-core', financeSemanticScore: 10, states: ['default', 'selected', 'positive', 'negative'], usage: 'Market candlestick, quote movement, chart entry, or trading direction.', forbidden: ['Use up/down tones only when representing real market direction.'], deprecated: false },
  chatFeedback: { ...base, providerIcon: 'Message01Icon', proProviderIcon: 'Message01Icon', category: 'support-ops', defaultSize: 20, allowedTones: ['brand', 'textMuted'], primaryTone: 'brand', secondaryTone: 'textDim', strokeWidth: 1.75, visualWeight: 'supporting', financeSemanticScore: 6, states: ['default', 'unread'], usage: 'Feedback or single conversation entry.', forbidden: ['Do not use for community group.'], deprecated: false },
  communityChat: { ...base, providerIcon: 'UserGroupIcon', proProviderIcon: 'UserGroupIcon', category: 'support-ops', defaultSize: 22, allowedTones: ['textMuted', 'down', 'brand'], primaryTone: 'textMuted', secondaryTone: 'brand', strokeWidth: 1.75, visualWeight: 'supporting', financeSemanticScore: 6, states: ['default', 'active'], usage: 'Community, group chat, or social trading discussions.', forbidden: ['Do not use for individual support ticket.'], deprecated: false },
  checkMark: { ...base, providerIcon: 'Tick02Icon', proProviderIcon: 'Tick02Icon', category: 'system-navigation', defaultSize: 12, allowedTones: ['panel', 'white', 'brand', 'down'], primaryTone: 'brand', secondaryTone: 'textDim', strokeWidth: 1.9, visualWeight: 'micro', financeSemanticScore: 6, states: ['checked', 'success'], usage: 'Checkbox or compact selected indicator.', forbidden: ['Do not use as full verification badge.'], deprecated: false },
  statusVerified: { ...base, providerIcon: 'CheckmarkCircle02Icon', proProviderIcon: 'CheckmarkCircle02Icon', category: 'kyc', defaultSize: 18, allowedTones: ['brand', 'down', 'text'], primaryTone: 'brand', secondaryTone: 'down', strokeWidth: 1.75, visualWeight: 'financial-core', financeSemanticScore: 9, states: ['verified', 'selected', 'success'], usage: 'Verified state, selected account, completed status.', forbidden: ['Do not use for generic checkbox when checkMark is enough.'], deprecated: false },
  historyClock: { ...base, providerIcon: 'TransactionHistoryIcon', proProviderIcon: 'TransactionHistoryIcon', category: 'trading', defaultSize: 18, allowedTones: ['text', 'textDim', 'amber'], primaryTone: 'text', secondaryTone: 'amber', strokeWidth: 1.75, visualWeight: 'financial-core', financeSemanticScore: 9, states: ['pending', 'default'], usage: 'Order history, transaction history, pending activity, or time filter.', forbidden: ['Do not use for countdown risk unless paired with warning tone.'], deprecated: false },
  discoverCompass: { ...base, providerIcon: 'CompassIcon', proProviderIcon: 'CompassIcon', category: 'system-navigation', defaultSize: 20, allowedTones: ['brand', 'textDim'], primaryTone: 'brand', secondaryTone: 'textDim', strokeWidth: 1.75, visualWeight: 'navigation', financeSemanticScore: 6, states: ['default', 'selected'], usage: 'Discover and module exploration entry.', forbidden: ['Do not use for location.'], deprecated: false },
  moreDots: { ...base, providerIcon: 'MoreHorizontalIcon', proProviderIcon: 'MoreHorizontalIcon', category: 'system-navigation', defaultSize: 22, allowedTones: ['text', 'textMuted'], primaryTone: 'textMuted', secondaryTone: 'textDim', strokeWidth: 1.7, visualWeight: 'micro', financeSemanticScore: 6, states: ['default', 'pressed'], usage: 'More actions menu.', forbidden: ['Do not use for loading.'], deprecated: false },
  emailMessage: { ...base, providerIcon: 'MailOpenIcon', proProviderIcon: 'MailOpenIcon', category: 'support-ops', defaultSize: 18, allowedTones: ['brand', 'textMuted'], primaryTone: 'brand', secondaryTone: 'textDim', strokeWidth: 1.75, visualWeight: 'supporting', financeSemanticScore: 6, states: ['default', 'sent', 'received'], usage: 'Email, inbox, password recovery.', forbidden: ['Do not use for app notifications.'], deprecated: false },
  rewardGift: { ...base, providerIcon: 'GiftIcon', proProviderIcon: 'GiftIcon', category: 'support-ops', defaultSize: 22, allowedTones: ['amber', 'brand'], primaryTone: 'amber', secondaryTone: 'textDim', strokeWidth: 1.75, visualWeight: 'supporting', financeSemanticScore: 5, states: ['default', 'available'], usage: 'Rewards, bonus, promotional gift.', forbidden: ['Do not use for trading ticket or account funds.'], deprecated: false },
  globalMarket: { ...base, providerIcon: 'GlobeIcon', proProviderIcon: 'GlobeIcon', category: 'market', defaultSize: 19, allowedTones: ['brand', 'panel'], primaryTone: 'brand', secondaryTone: 'textDim', strokeWidth: 1.75, visualWeight: 'financial-core', financeSemanticScore: 8, states: ['default', 'selected'], usage: 'Global market, language, regional onboarding.', forbidden: ['Do not use for account identity.'], deprecated: false },
  educationCap: { ...base, providerIcon: 'School01Icon', proProviderIcon: 'School01Icon', category: 'support-ops', defaultSize: 20, allowedTones: ['brand', 'textDim'], primaryTone: 'brand', secondaryTone: 'textDim', strokeWidth: 1.75, visualWeight: 'supporting', financeSemanticScore: 6, states: ['default', 'completed'], usage: 'Education, academy, trading lessons.', forbidden: ['Do not use for KYC completion.'], deprecated: false },
  supportHeadset: { ...base, providerIcon: 'HeadsetIcon', proProviderIcon: 'HeadsetIcon', category: 'support-ops', defaultSize: 18, allowedTones: ['textMuted', 'brand'], primaryTone: 'textMuted', secondaryTone: 'brand', strokeWidth: 1.75, visualWeight: 'supporting', financeSemanticScore: 6, states: ['default', 'available'], usage: 'Support center or service contact.', forbidden: ['Do not use for audio/media.'], deprecated: false },
  identityCard: { ...base, providerIcon: 'UserIdVerificationIcon', proProviderIcon: 'UserIdVerificationIcon', category: 'kyc', defaultSize: 20, allowedTones: ['down', 'brand', 'text'], primaryTone: 'brand', secondaryTone: 'down', strokeWidth: 1.75, visualWeight: 'financial-core', financeSemanticScore: 10, states: ['default', 'reviewing', 'verified'], usage: 'Identity verification, onboarding KYC, profile document.', forbidden: ['Do not use for generic account tab.'], deprecated: false },
  infoCircle: { ...base, providerIcon: 'InformationCircleIcon', proProviderIcon: 'InformationCircleIcon', category: 'risk', defaultSize: 15, allowedTones: ['textMuted', 'blue', 'danger'], primaryTone: 'textMuted', secondaryTone: 'blue', strokeWidth: 1.7, visualWeight: 'micro', financeSemanticScore: 8, states: ['default', 'warning', 'error'], usage: 'Inline help, disclosure, risk explanation.', forbidden: ['Do not use as success status.'], deprecated: false },
  quoteList: { ...base, providerIcon: 'ListViewIcon', proProviderIcon: 'ListViewIcon', category: 'market', defaultSize: 20, allowedTones: ['text', 'textDim'], primaryTone: 'text', secondaryTone: 'textDim', strokeWidth: 1.75, visualWeight: 'financial-core', financeSemanticScore: 8, states: ['default', 'selected'], usage: 'Watchlist, quote list, list view.', forbidden: ['Do not use for task checklist.'], deprecated: false },
  taskChecklist: { ...base, providerIcon: 'CheckListIcon', proProviderIcon: 'CheckListIcon', category: 'trading', defaultSize: 20, allowedTones: ['brand', 'text', 'textDim'], primaryTone: 'brand', secondaryTone: 'textDim', strokeWidth: 1.75, visualWeight: 'financial-core', financeSemanticScore: 8, states: ['default', 'completed'], usage: 'Orders, trading journal, task checklist, execution list.', forbidden: ['Do not use for plain market quote list.'], deprecated: false },
  secureLock: { ...base, providerIcon: 'SecurityLockIcon', proProviderIcon: 'SecurityLockIcon', category: 'risk', defaultSize: 16, allowedTones: ['textDim', 'brand'], primaryTone: 'textDim', secondaryTone: 'brand', strokeWidth: 1.7, visualWeight: 'financial-core', financeSemanticScore: 9, states: ['locked', 'secure', 'disabled'], usage: 'Password, locked field, protected content.', forbidden: ['Do not use for regulatory review.'], deprecated: false },
  searchGlass: { ...base, providerIcon: 'Search01Icon', proProviderIcon: 'Search01Icon', category: 'system-navigation', defaultSize: 17, allowedTones: ['text', 'textDim'], primaryTone: 'text', secondaryTone: 'textDim', strokeWidth: 1.7, visualWeight: 'navigation', financeSemanticScore: 6, states: ['default', 'focused', 'disabled'], usage: 'Search entry and field prefix.', forbidden: ['Do not use for inspect/detail navigation.'], deprecated: false },
  qrCode: { ...base, providerIcon: 'QrCodeIcon', proProviderIcon: 'QrCodeIcon', category: 'funds', defaultSize: 24, allowedTones: ['text', 'brand'], primaryTone: 'text', secondaryTone: 'brand', strokeWidth: 1.8, visualWeight: 'financial-core', financeSemanticScore: 9, states: ['default', 'scanned'], usage: 'Deposit QR, account QR, scan code.', forbidden: ['Do not use for generic code/coupon.'], deprecated: false },
  partnerNetwork: { ...base, providerIcon: 'Share08Icon', proProviderIcon: 'Share08Icon', category: 'support-ops', defaultSize: 20, allowedTones: ['brand', 'blue', 'text'], primaryTone: 'brand', secondaryTone: 'blue', strokeWidth: 1.75, visualWeight: 'supporting', financeSemanticScore: 6, states: ['default', 'active'], usage: 'Partner network, sharing, referral graph.', forbidden: ['Do not use for transfer funds.'], deprecated: false },
  riskShield: { ...base, providerIcon: 'SecurityCheckIcon', proProviderIcon: 'SecurityCheckIcon', category: 'risk', defaultSize: 18, allowedTones: ['brand', 'down', 'textMuted'], primaryTone: 'brand', secondaryTone: 'down', strokeWidth: 1.75, visualWeight: 'financial-core', financeSemanticScore: 10, states: ['protected', 'verified', 'reviewing'], usage: 'Security, fraud prevention, compliance protection.', forbidden: ['Do not use as generic success when statusVerified is clearer.'], deprecated: false },
  settingsSliders: { ...base, providerIcon: 'FilterHorizontalIcon', proProviderIcon: 'FilterHorizontalIcon', category: 'system-navigation', defaultSize: 18, allowedTones: ['brand', 'textDim'], primaryTone: 'textDim', secondaryTone: 'brand', strokeWidth: 1.75, visualWeight: 'functional', financeSemanticScore: 7, states: ['default', 'active'], usage: 'Settings, filters, product controls, sort.', forbidden: ['Do not use for market depth.'], deprecated: false },
  promoTicket: { ...base, providerIcon: 'TicketStarIcon', proProviderIcon: 'TicketStarIcon', category: 'support-ops', defaultSize: 20, allowedTones: ['amber', 'textDim'], primaryTone: 'amber', secondaryTone: 'textDim', strokeWidth: 1.75, visualWeight: 'supporting', financeSemanticScore: 5, states: ['default', 'available', 'expired'], usage: 'Coupon, promotion, simulated contest badge.', forbidden: ['Do not use for trading order ticket; use taskChecklist.'], deprecated: false },
  achievementTrophy: { ...base, providerIcon: 'Award01Icon', proProviderIcon: 'Award01Icon', category: 'support-ops', defaultSize: 20, allowedTones: ['amber', 'textDim'], primaryTone: 'amber', secondaryTone: 'textDim', strokeWidth: 1.75, visualWeight: 'supporting', financeSemanticScore: 5, states: ['default', 'earned'], usage: 'Challenge, leaderboard, achievement.', forbidden: ['Do not use for account status.'], deprecated: false },
  userProfile: { ...base, providerIcon: 'UserIcon', proProviderIcon: 'UserIcon', category: 'account', defaultSize: 22, allowedTones: ['text', 'blue'], primaryTone: 'text', secondaryTone: 'blue', strokeWidth: 1.75, visualWeight: 'functional', financeSemanticScore: 7, states: ['default', 'selected'], usage: 'User, client, account owner, profile preview.', forbidden: ['Do not use for bank/funding account.'], deprecated: false },
  userAvatar: { ...base, providerIcon: 'UserCircleIcon', proProviderIcon: 'UserCircleIcon', category: 'account', defaultSize: 22, allowedTones: ['text', 'textMuted'], primaryTone: 'text', secondaryTone: 'textDim', strokeWidth: 1.75, visualWeight: 'functional', financeSemanticScore: 7, states: ['default', 'selected'], usage: 'Profile avatar placeholder and profile module.', forbidden: ['Do not use for add-account action.'], deprecated: false },
  addUser: { ...base, providerIcon: 'UserAdd01Icon', proProviderIcon: 'UserAdd01Icon', category: 'account', defaultSize: 22, allowedTones: ['text', 'brand'], primaryTone: 'text', secondaryTone: 'brand', strokeWidth: 1.75, visualWeight: 'functional', financeSemanticScore: 7, states: ['default', 'pressed'], usage: 'Add account, add client, invite user.', forbidden: ['Do not use for KYC verification.'], deprecated: false },
  closeX: { ...base, providerIcon: 'Cancel01Icon', proProviderIcon: 'Cancel01Icon', category: 'system-navigation', defaultSize: 16, allowedTones: ['textDim', 'danger', 'panel'], primaryTone: 'textDim', secondaryTone: 'danger', strokeWidth: 1.75, visualWeight: 'micro', financeSemanticScore: 6, states: ['default', 'pressed', 'destructive'], usage: 'Close, cancel, dismiss, delete when paired with danger tone.', forbidden: ['Do not use as failed status without label.'], deprecated: false },
} as const satisfies Record<string, AppIconDefinition>;

export type AppIconName = keyof typeof iconRegistry;

export function resolveIconTone(palette: ThemePalette, tone: IconTone | string): string {
  return palette[tone as keyof ThemePalette] ?? tone;
}
